const STORAGE_KEY='svw_countries_v2';
const PREVIOUS_KEY='svw_previous_v2';
const countries=JSON.parse(localStorage.getItem(STORAGE_KEY)) || window.DEFAULT_COUNTRIES;
const previous=JSON.parse(localStorage.getItem(PREVIOUS_KEY)) || null;
function flagUrl(code){return `https://flagcdn.com/w80/${code}.png`}
function avg(c){return (Number(c.official)+Number(c.world))/2}
function formatOdds(n){return Number(n).toFixed(2).replace(/\.00$/,'')}
function chances(list){const weights=list.map(c=>1/avg(c));const total=weights.reduce((a,b)=>a+b,0);let raw=weights.map(w=>w/total*100);return raw.map(v=>v<1?'<1%':`${Math.round(v)}%`)}
function render(){const list=[...countries].sort((a,b)=>a.rank-b.rank);const chance=chances(list);const body=document.getElementById('oddsBody');body.innerHTML='';list.forEach((c,i)=>{const p=previous?.find(x=>x.name===c.name);const rankMove=p?p.rank-c.rank:0;const officialDiff=p?Number(p.official)-Number(c.official):0;const worldDiff=p?Number(p.world)-Number(c.world):0;const tr=document.createElement('tr');tr.innerHTML=`<td class="rank-cell">${c.rank}${rankMove>0?'<span class="move up">▲</span>':rankMove<0?'<span class="move down">▼</span>':'<span class="move same">–</span>'}</td><td><button class="country-button" data-country="${c.name}"><img class="flag" src="${flagUrl(c.code)}" alt="${c.name}"><span class="country-name">${c.name}</span>${c.released?'<span class="video">▶</span>':''}</button></td><td class="chance">${chance[i]}</td><td><span class="odds-box ${officialDiff>0?'flash-good':officialDiff<0?'flash-bad':''}">${formatOdds(c.official)}</span></td><td><span class="odds-box ${worldDiff>0?'flash-good':worldDiff<0?'flash-bad':''}">${formatOdds(c.world)}</span></td><td><button class="history-btn" data-country="${c.name}">📈</button></td>`;body.appendChild(tr)});document.querySelectorAll('[data-country]').forEach(btn=>btn.addEventListener('click',()=>openModal(btn.dataset.country)));document.getElementById('lastUpdated').textContent='Last updated: '+new Date().toLocaleString('en-GB')}
function openModal(name){const c=countries.find(x=>x.name===name);document.getElementById('modalFlag').src=flagUrl(c.code);document.getElementById('modalCountry').textContent=c.name;document.getElementById('modalStatus').textContent=c.released?'Released ▶':'Not released yet';document.getElementById('modalArtist').textContent=c.artist||'TBA';document.getElementById('modalSong').textContent=c.song||'TBA';document.getElementById('modalRelease').textContent=c.releaseDate||'TBA';document.getElementById('modalRank').textContent='#'+c.rank;document.getElementById('modalHistory').textContent=c.history||'No history yet.';document.getElementById('countryModal').classList.add('open')}
document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>document.getElementById('countryModal').classList.remove('open')));render();
