window.DEFAULT_COUNTRIES = [
  {rank:1,name:'Finland',code:'fi',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:1.85,world:1.75,history:'Initial market leader.'},
  {rank:2,name:'Australia',code:'au',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:4.50,world:4.50,history:'Song released on 28th May.'},
  {rank:3,name:'Bulgaria',code:'bg',artist:'TBA',song:'TBA',releaseDate:'11th June',released:false,official:9.00,world:7.50,history:'Release expected on 11th June.'},
  {rank:4,name:'Sweden',code:'se',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:34,world:34,history:'Song released on 28th May.'},
  {rank:5,name:'Romania',code:'ro',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:34,world:34,history:'Song released on 28th May.'},
  {rank:6,name:'Greece',code:'gr',artist:'TBA',song:'TBA',releaseDate:'14th June',released:false,official:23,world:31,history:'Release expected on 14th June.'},
  {rank:7,name:'Cyprus',code:'cy',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:201,world:201,history:'Song released on 28th May.'},
  {rank:8,name:'Poland',code:'pl',artist:'TBA',song:'TBA',releaseDate:'1st June',released:false,official:251,world:251,history:'Release expected on 1st June.'},
  {rank:9,name:'Serbia',code:'rs',artist:'TBA',song:'TBA',releaseDate:'2nd June',released:false,official:251,world:201,history:'Release expected on 2nd June.'},
  {rank:10,name:'Germany',code:'de',artist:'TBA',song:'TBA',releaseDate:'31st May',released:false,official:251,world:301,history:'Release expected on 31st May.'},
  {rank:11,name:'Moldova',code:'md',artist:'TBA',song:'TBA',releaseDate:'4th June',released:false,official:101,world:101,history:'Release expected on 4th June.'},
  {rank:12,name:'Malta',code:'mt',artist:'TBA',song:'TBA',releaseDate:'10th June',released:false,official:81,world:101,history:'Release expected on 10th June.'},
  {rank:13,name:'Denmark',code:'dk',artist:'TBA',song:'TBA',releaseDate:'13th June',released:false,official:41,world:51,history:'Release expected on 13th June.'},
  {rank:14,name:'Albania',code:'al',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:201,world:151,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:15,name:'Croatia',code:'hr',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:151,world:151,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:16,name:'United Kingdom',code:'gb',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:301,world:301,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:17,name:'Switzerland',code:'ch',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:151,world:151,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:18,name:'Slovenia',code:'si',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:151,world:151,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:19,name:'Georgia',code:'ge',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:151,world:151,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:20,name:'San Marino',code:'sm',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:251,world:251,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:21,name:'Algeria',code:'dz',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:251,world:251,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:22,name:'Trinidad & Tobago',code:'tt',artist:'TBA',song:'TBA',releaseDate:'TBA',released:false,official:251,world:251,history:'Added to SPIRITVISIONWORLD odds.'},
  {rank:23,name:'Madagascar',code:'mg',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:301,world:301,history:'Song released on 28th May.'},
  {rank:24,name:'Latvia',code:'lv',artist:'TBA',song:'TBA',releaseDate:'28th May',released:true,official:301,world:301,history:'Song released on 28th May.'},
  {rank:25,name:'Azerbaijan',code:'az',artist:'TBA',song:'TBA',releaseDate:'29th May',released:false,official:301,world:301,history:'Release expected on 29th May.'},
  {rank:26,name:'Armenia',code:'am',artist:'TBA',song:'TBA',releaseDate:'30th May',released:false,official:301,world:301,history:'Release expected on 30th May.'},
  {rank:27,name:'Slovakia',code:'sk',artist:'TBA',song:'TBA',releaseDate:'30th May',released:false,official:301,world:301,history:'Release expected on 30th May.'},
  {rank:28,name:'Ireland',code:'ie',artist:'TBA',song:'TBA',releaseDate:'2nd June',released:false,official:301,world:301,history:'Release expected on 2nd June.'},
  {rank:29,name:'Spain',code:'es',artist:'TBA',song:'TBA',releaseDate:'2nd June',released:false,official:301,world:301,history:'Release expected on 2nd June.'},
  {rank:30,name:'Belgium',code:'be',artist:'TBA',song:'TBA',releaseDate:'6th June',released:false,official:301,world:301,history:'Release expected on 6th June.'},
  {rank:31,name:'Portugal',code:'pt',artist:'TBA',song:'TBA',releaseDate:'7th May',released:false,official:301,world:301,history:'Release expected on 7th May.'},
  {rank:32,name:'Montenegro',code:'me',artist:'TBA',song:'TBA',releaseDate:'8th May',released:false,official:301,world:301,history:'Release expected on 8th May.'},
  {rank:33,name:'Morocco',code:'ma',artist:'TBA',song:'TBA',releaseDate:'10th June',released:false,official:301,world:301,history:'Release expected on 10th June.'},
  {rank:34,name:'Iceland',code:'is',artist:'TBA',song:'TBA',releaseDate:'11th June',released:false,official:301,world:301,history:'Release expected on 11th June.'},
  {rank:35,name:'Vietnam',code:'vn',artist:'TBA',song:'TBA',releaseDate:'12th June',released:false,official:301,world:301,history:'Release expected on 12th June.'},
  {rank:36,name:'Puerto Rico',code:'pr',artist:'TBA',song:'TBA',releaseDate:'12th June',released:false,official:301,world:301,history:'Release expected on 12th June.'},
  {rank:37,name:'Estonia',code:'ee',artist:'TBA',song:'TBA',releaseDate:'14th June',released:false,official:301,world:301,history:'Release expected on 14th June.'}
];
